### ISSUE TITLE
Compiles successfully but throws an error

### ISSUE THREAD

**Issue by eladams** [thusfresh/relay-compiler-webpack-plugin#5]
```
(node:10835) TypeError: Cannot read property 'push' of undefined
    at Compiler.<anonymous> (/Users/elad/dev/isplayin/core/node_modules/relay-compiler-webpack-plugin/dist/index.js:86:29)
    at Generator.throw (<anonymous>)
    at step (/Users/elad/dev/isplayin/core/node_modules/relay-compiler-webpack-plugin/dist/index.js:23:191)
    at /Users/elad/dev/isplayin/core/node_modules/relay-compiler-webpack-plugin/dist/index.js:23:402
    at process._tickCallback (internal/process/next_tick.js:109:7)
(node:10835) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitWarning (internal/process/promises.js:69:15)
    at emitPendingUnhandledRejections (internal/process/promises.js:86:11)
    at process._tickCallback (internal/process/next_tick.js:110:7)
```

**Comment by danielholmes** [comment]
Some extra info on this. In `compilation.errors` errors is undefined. I've tried this for webpack 2.6.1 and 3.0.0. I tried passing the error to the callback instead but that leaves the compilation hanging after displaying the error, so a better result but not perfect:

```js
try {
  const runner = new _relayCompiler.Runner({
    parserConfigs: _this.parserConfigs,
    writerConfigs: _this.writerConfigs,
    onlyValidate: false,
    skipPersist: true
  });
  yield runner.compileAll();
} catch (error) {
  callback(error);
  return;
}
callback();
```

Seems the error was introduced here: https://github.com/thusfresh/relay-compiler-webpack-plugin/commit/373f1f268ef52e768940b2659594df93bc850578 (NOTE that `'before-compile'` is passed `compilationParams` instead of `compilation`, see https://webpack.js.org/api/plugins/compiler/#event-hooks )

**Comment by ryanblakeley** [comment]
I'm getting the same error but I don't think it is successfully compiling. I have to run my relay compiler script manually before running the app or it doesn't find the expected `__generated__` files.
